version: "3.9"

services:
  prometheus-container:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
     - '9090:9090'
    volumes:
     - './prometheus.yml:/etc/prometheus/prometheus.yml'
     - 'prometheus-data:/prometheus'
    restart: always
  go-app:
    build: .
    container_name: go-app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "8081:8081"
volumes:
  prometheus-data: {}
